# Generated by Django 3.1.4 on 2020-12-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201218_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_category',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
