# Generated by Django 3.1.4 on 2020-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201218_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bids_product',
            field=models.CharField(max_length=64),
        ),
    ]
