# Generated by Django 3.1.4 on 2020-12-19 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201219_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_pubdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
