# Generated by Django 3.1.4 on 2020-12-19 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments_comments_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_pubdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
